
export const ITEM_CBM_DEFAULTS = {
  "Wohnzimmer": [
    { key: "sitzlandschaft", name: "Sitzlandschaft (Element), je Sitz", cbm: 0.4 },
    { key: "sesselMitArmlehnenWZ", name: "Sessel, mit Armlehnen", cbm: 0.8 },
    { key: "sesselOhneArmlehnenWZ", name: "Sessel, ohne Armlehnen", cbm: 0.4 },
    { key: "stuhlWZ", name: "Stuhl", cbm: 0.2 },
    { key: "stuhlMitArmlehnenWZ", name: "Stuhl, mit Armlehnen", cbm: 0.3 },
    { key: "tischBis0_6mWZ", name: "Tisch, bis 0,6 m", cbm: 0.4 },
    { key: "tischBis1_0mWZ", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis1_2mWZ", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischUeber1_2mWZ", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "wohnzimmerschrank", name: "Wohnz.-Schrank, zerlegb. je angef. m", cbm: 0.8 },
    { key: "anbauwandBis38cm", name: "Anbauwand b.38 cm Tiefe je angef.m", cbm: 0.8 },
    { key: "anbauwandUeber38cm", name: "Anbauwand ü. 38 cm Tiefe je angef. m", cbm: 1.0 },
    { key: "buecherregal", name: "Bücherregal, zerlegbar je angef. m", cbm: 0.4 },
    { key: "buffetMitAufsatz", name: "Buffet, mit Aufsatz", cbm: 1.8 },
    { key: "standuhr", name: "Standuhr", cbm: 0.4 },
    { key: "schreibtischBis1_6mWZ", name: "Schreibtisch, bis 1,6 m", cbm: 1.2 },
    { key: "schreibtischUeber1_6mWZ", name: "Schreibtisch, über 1,6 m", cbm: 1.7 },
    { key: "sekretaer", name: "Sekretär", cbm: 0.8 },
    { key: "sideboardWZ", name: "Sideboard", cbm: 1.2 },
    { key: "musikschrank", name: "Musikschrank / Turm", cbm: 0.4 },
    { key: "fernseher", name: "Fernseher", cbm: 0.3 },
    { key: "klavier", name: "Klavier", cbm: 1.5 },
    { key: "fluegel", name: "Flügel", cbm: 2.0 },
    { key: "phonoTVMoebel", name: "Phono/TV Möbel", cbm: 0.4 },
    { key: "naehmaschine", name: "Nähmaschine(Schrank)", cbm: 0.4 },
    { key: "stehlampe", name: "Stehlampe", cbm: 0.2 },
    { key: "bilderUeber0_8m", name: "Bilder, über 0,8 m", cbm: 0.2 },
    { key: "deckenlampeWZ", name: "Deckenlampe", cbm: 0.2 },
    { key: "luester", name: "Lüster", cbm: 0.5 },
    { key: "teppichWZ", name: "Teppich", cbm: 0.3 },
    { key: "brueckeWZ", name: "Brücke", cbm: 0.1 },
    { key: "computer", name: "Computer BS,Drucker", cbm: 0.3 },
    { key: "blumenKlein", name: "5 Blumen klein bis 30cm", cbm: 0.1 },
    { key: "blumenMittel", name: "Blumen mittel bis 1,40m", cbm: 0.1 },
    { key: "blumenGross", name: "Blumen groß bis 2 m", cbm: 0.2 },

    // Aliase / ungemappte Wohnzimmer-Keys
    { key: "buecherregalZerlegbarJeAngefM", name: "Bücherregal, zerlegbar je angef. m", cbm: 0.4 },
    { key: "buecherregalZerlegbJeAngefM", name: "Bücherregal, zerlegbar je angef. m", cbm: 0.4 },
    { key: "tischBis-06MWz", name: "Tisch, bis 0,6 m", cbm: 0.4 },
    { key: "tischBis-10MWz", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis-12MWz", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischUeber-12MWz", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "teppichWz", name: "Teppich", cbm: 0.3 },
    { key: "deckenlampeWz", name: "Deckenlampe", cbm: 0.2 },
    { key: "brueckeWz", name: "Brücke", cbm: 0.1 },
    { key: "wohnzSchrankZerlegbJeAngefM", name: "Wohnz.-Schrank, zerlegb. je angef. m", cbm: 0.8 },
    { key: "anbauwandB38CmTiefeJeAngefm", name: "Anbauwand b.38 cm Tiefe je angef.m", cbm: 0.8 },
    { key: "anbauwandBis-38CmTiefeJeAngefM", name: "Anbauwand b.38 cm Tiefe je angef.m", cbm: 0.8 },
    { key: "anbauwandUeb-38CmTiefeJeAngefM", name: "Anbauwand ü. 38 cm Tiefe je angef. m", cbm: 1.0 },
    { key: "anbauwandUe-38CmTiefeJeAngefM", name: "Anbauwand ü. 38 cm Tiefe je angef. m", cbm: 1.0 },
    { key: "bilderUeber-08M", name: "Bilder, über 0,8 m", cbm: 0.2 },
    { key: "bilderueber-080M", name: "Bilder, über 0,8 m", cbm: 0.2 },
    { key: "computerBsdrucker", name: "Computer BS, Drucker", cbm: 0.3 },
    { key: "naehmaschineschrank", name: "Nähmaschine (Schrank)", cbm: 0.4 },
    { key: "musikschrank-/Turm", name: "Musikschrank / Turm", cbm: 0.4 },
    { key: "phono/TVMoebel", name: "Phono/TV Möbel", cbm: 0.4 },
    { key: "5BlumenKleinBis-30cm", name: "5 Blumen klein bis 30cm", cbm: 0.1 },
    { key: "blumenMittelBis-140m", name: "Blumen mittel bis 1,40m", cbm: 0.1 },
    { key: "blumenGrossBis-2M", name: "Blumen groß bis 2 m", cbm: 0.2 },
    { key: "sideboardWz", name: "Sideboard", cbm: 1.2 },
    { key: "sesselMitArmlehnenWz", name: "Sessel, mit Armlehnen", cbm: 0.8 },
    { key: "sesselOhneArmlehnenWz", name: "Sessel, ohne Armlehnen", cbm: 0.4 },
    { key: "schreibtischUeber-16MWz", name: "Schreibtisch, über 1,6 m", cbm: 1.7 },
    { key: "schreibtischBis-16MWz", name: "Schreibtisch, bis 1,6 m", cbm: 1.2 },
    { key: "sitzlandschaftElementJeSitz-", name: "Sitzlandschaft (Element), je Sitz", cbm: 0.4 }
  ],

  "Schlafzimmer": [
    { key: "schrankBis2TuerenSZ", name: "Schrank, bis 2 Türen, nicht zerlegbar", cbm: 1.5 },
    { key: "schrankZerlegbarSZ", name: "Schrank, zerlegbar, je angef. m", cbm: 0.8 },
    { key: "doppelbett", name: "Doppelbett, komplett", cbm: 2.0 },
    { key: "einzelbett", name: "Einzelbett, komplett", cbm: 1.0 },
    { key: "franzBett", name: "Franz. Bett, komplett, Futonbett", cbm: 1.5 },
    { key: "bettzeug", name: "Bettzeug, je Betteinheit", cbm: 0.3 },
    { key: "nachttischSZ", name: "Nachttisch", cbm: 0.2 },
    { key: "bettumbau", name: "Bettumbau", cbm: 0.3 },
    { key: "kommodeSZ", name: "Kommode", cbm: 0.7 },
    { key: "frisierkommode", name: "Frisierkommode, mit Spiegel", cbm: 0.6 },
    { key: "waeschetruhe", name: "Wäschetruhe", cbm: 0.3 },
    { key: "stuhlHockerSZ", name: "Stuhl, Hocker", cbm: 0.2 },
    { key: "spiegelUeber0_8m", name: "Spiegel, über 0,8 m", cbm: 0.1 },
    { key: "deckenlampeSZ", name: "Deckenlampe", cbm: 0.2 },
    { key: "bilderUeber0_80mSZ", name: "Bilder, über 0,80 m", cbm: 0.2 },
    { key: "blumenGroesseSZ", name: "Blumen Größe", cbm: 0.2 },

    // Aliase Schlafzimmer
    { key: "schrankBis-2TuerenNichtZerlegbar", name: "Schrank, bis 2 Türen, nicht zerlegbar", cbm: 1.5 },
    { key: "schrankZerlegbarJeAngefM", name: "Schrank, zerlegbar, je angef. m", cbm: 0.8 },
    { key: "doppelbettKomplett", name: "Doppelbett, komplett", cbm: 2.0 },
    { key: "einzelbettKomplett", name: "Einzelbett, komplett", cbm: 1.0 },
    { key: "franzBettKomplettFutonbett", name: "Franz. Bett, komplett, Futonbett", cbm: 1.5 },
    { key: "bettKomplett", name: "Bett, komplett", cbm: 1.0 },
    { key: "bettzeugJeBetteinheit", name: "Bettzeug, je Betteinheit", cbm: 0.3 },
    { key: "nachttisch", name: "Nachttisch", cbm: 0.2 },
    { key: "kommode", name: "Kommode", cbm: 0.7 },
    { key: "frisierkommodeMitSpiegel", name: "Frisierkommode, mit Spiegel", cbm: 0.6 },
    { key: "spiegelUeber-08M", name: "Spiegel, über 0,8 m", cbm: 0.1 }
  ],

  "Küche": [
    { key: "buffetMitAufsatzKueche", name: "Buffet m.Aufsätzen", cbm: 1.8 },
    { key: "unterteilKueche", name: "Unterteil,je Tür", cbm: 0.4 },
    { key: "oberteilKueche", name: "Oberteil, je Tür", cbm: 0.4 },
    { key: "tischBis0_6mK", name: "Tisch, bis 0,6 m", cbm: 0.4 },
    { key: "tischBis1_0mK", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis1_2mK", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischUeber1_2mK", name: "Tisch, über 1,2m", cbm: 0.8 },
    { key: "stuhlK", name: "Stuhl", cbm: 0.2 },
    { key: "eckbankK", name: "Eckbank, je Sitz", cbm: 0.2 },
    { key: "besenschrank", name: "Besenschrank", cbm: 0.6 },
    { key: "herdMikrowelle", name: "Herd / Mikrowelle", cbm: 0.5 },
    { key: "geschirrspuelmaschine", name: "Geschirrspülmaschine", cbm: 0.5 },
    { key: "waschmaschineTrockner", name: "Waschmaschine /Trockner", cbm: 0.5 },
    { key: "kuehlschrankBis120l", name: "Kühlschrank / Truhe, bis 120 l", cbm: 0.5 },
    { key: "kuehlschrankUeber120l", name: "Kühlschrank / Truhe, über 120 l", cbm: 1.0 },
    { key: "arbeitsplatte", name: "Arbeitsplatte, nicht unterb., je angf. m", cbm: 0.1 },
    { key: "deckenlampeK", name: "Deckenlampe", cbm: 0.2 },
    { key: "teppichK", name: "Teppich", cbm: 0.3 },

    // Aliase Küche
    { key: "kuehlschrank-/TruheBis-120L", name: "Kühlschrank / Truhe, bis 120 l", cbm: 0.5 },
    { key: "kuehlschrank-/TruheUeber-120L", name: "Kühlschrank / Truhe, über 120 l", cbm: 1.0 },
    { key: "arbeitsplatteNichtUnterbJeAngfM", name: "Arbeitsplatte, nicht unterb., je angf. m", cbm: 0.1 },
    { key: "eckbankJeSitz", name: "Eckbank, je Sitz", cbm: 0.2 },
    { key: "waschmaschine-/trockner", name: "Waschmaschine /Trockner", cbm: 0.5 },
    { key: "herd-/Mikrowelle", name: "Herd / Mikrowelle", cbm: 0.5 },
    { key: "unterteiljeTuer", name: "Unterteil, je Tür", cbm: 0.4 },
    { key: "oberteilJeTuer", name: "Oberteil, je Tür", cbm: 0.4 },
    { key: "buffetMaufsaetzen", name: "Buffet m.Aufsätzen", cbm: 1.8 },
    { key: "tischUeber-12mK", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "tischBis-12MK", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischBis-06MK", name: "Tisch, bis 0,6 m", cbm: 0.4 },
    { key: "tischBis-10MK", name: "Tisch, bis 1,0 m", cbm: 0.5 }
  ],

  "Esszimmer": [
    { key: "stuhlEZ", name: "Stuhl", cbm: 0.2 },
    { key: "stuhlMitArmlehnenEZ", name: "Stuhl, mit Armlehnen", cbm: 0.3 },
    { key: "eckbankEZ", name: "Eckbank, pro Sitz", cbm: 0.2 },
    { key: "tischBis1_0mEZ", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis1_2mEZ", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischUeber1_2mEZ", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "buffetOhneAufsatz", name: "Buffet, ohne Aufsatz", cbm: 1.5 },
    { key: "vitrine", name: "Vitrine (Glasschrank)", cbm: 1.0 },
    { key: "sideboardEZ", name: "Sideboard", cbm: 1.2 },
    { key: "hausbar", name: "Hausbar", cbm: 0.5 },
    { key: "teewagen", name: "Teewagen, nicht zerlegbar", cbm: 0.4 },
    { key: "teppichEZ", name: "Teppich", cbm: 0.3 },
    { key: "brueckeEZ", name: "Brücke", cbm: 0.1 },
    { key: "deckenlampeEZ", name: "Deckenlampe", cbm: 0.2 },
    { key: "blumenGroesseEZ", name: "Blumen Größe", cbm: 0.1 },

    // Aliase Esszimmer
    { key: "sideboard", name: "Sideboard", cbm: 1.2 },
    { key: "vitrineGlasschrank", name: "Vitrine (Glasschrank)", cbm: 1.0 },
    { key: "tischBis-12MEz", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischBis-10MEz", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischUeber-12MEz", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "teppichEz", name: "Teppich", cbm: 0.3 },
    { key: "deckenlampeEz", name: "Deckenlampe", cbm: 0.2 },
    { key: "teewagenNichtZerlegbar", name: "Teewagen, nicht zerlegbar", cbm: 0.4 },
    { key: "eckbankProSitz", name: "Eckbank, pro Sitz", cbm: 0.2 }
  ],

  "Bad": [
    { key: "truheKommodeDiele", name: "Truhe,Kommode,Schuhschrank", cbm: 0.2 },
    { key: "hutKleiderablage", name: "Hut- / Kleiderablage", cbm: 0.2 },
    { key: "stuhlHockerDiele", name: "Stuhl / Hocker", cbm: 0.2 },
    { key: "toilettenschrank", name: "Toilettenschrank", cbm: 0.2 },
    { key: "waeschepuff", name: "Wäschepuff", cbm: 0.2 },
    { key: "teppichBZ", name: "Teppich", cbm: 0.2 },
    { key: "deckenlampeBZ", name: "Deckenlampe", cbm: 0.2 },

    // Aliase Bad/Diele
    { key: "teppichBz", name: "Teppich", cbm: 0.2 },
    { key: "deckenlampeBz", name: "Deckenlampe", cbm: 0.2 },
    { key: "hut--/Kleiderablage", name: "Hut- / Kleiderablage", cbm: 0.2 },
    { key: "truhekommodeschuhschrank", name: "Truhe,Kommode,Schuhschrank", cbm: 0.2 },
    { key: "stuhlHocker", name: "Stuhl / Hocker", cbm: 0.2 }
  ],

  "Büro": [
    { key: "schreibtischBis1_6mAZ", name: "Schreibtisch, bis 1,6 m", cbm: 1.2 },
    { key: "schreibtischUeber1_6mAZ", name: "Schreibtisch, über 1,6 m", cbm: 1.7 },
    { key: "schreibtischstuhl", name: "Schreibtischstuhl", cbm: 0.3 },
    { key: "buecherregalAZ", name: "Bücherregal, zerlegb. je angef. m", cbm: 0.4 },
    { key: "aktenschrank", name: "Aktenschrank, je angef.m", cbm: 0.8 },
    { key: "buecherregalNiederAZ", name: "Bücherregal nieder", cbm: 0.2 },
    { key: "sesselOhneArmlehnenAZ", name: "Sessel.ohne Armlehnen", cbm: 0.4 },
    { key: "sesselMitArmlehnenAZ", name: "Sessel, mit Armlehnen", cbm: 0.8 },
    { key: "rollcontainer", name: "Rollcontainer", cbm: 0.3 },
    { key: "tischBis1_0mAZ", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis1_2mAZ", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischUeber1_2mAZ", name: "Tisch,über 1,2 m", cbm: 0.8 },
    { key: "deckenlampeAZ", name: "Deckenlampe", cbm: 0.2 },
    { key: "teppichAZ", name: "Teppich", cbm: 0.3 },
    { key: "brueckeAZ", name: "Brücke", cbm: 0.1 },
    { key: "pcMonitorDruckerAZ", name: "PC + Monitor +Kleindrucker", cbm: 0.3 },

    // Aliase Büro
    { key: "aktenschrankJeAngefm", name: "Aktenschrank, je angef.m", cbm: 0.8 },
    { key: "pc-+Monitor-+kleindruckerAz", name: "PC + Monitor + Kleindrucker", cbm: 0.3 },
    { key: "tischBis-10MAz", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "tischBis-12MAz", name: "Tisch, bis 1,2 m", cbm: 0.6 },
    { key: "tischueber-12MAz", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "schreibtischUeber-16MAz", name: "Schreibtisch, über 1,6 m", cbm: 1.7 },
    { key: "schreibtischBis-16MAz", name: "Schreibtisch, bis 1,6 m", cbm: 1.2 },
    { key: "sesselMitArmlehnenAz", name: "Sessel, mit Armlehnen", cbm: 0.8 },
    { key: "sesselohneArmlehnenAz", name: "Sessel, ohne Armlehnen", cbm: 0.4 },
    { key: "teppichAz", name: "Teppich", cbm: 0.3 },
    { key: "brueckeAz", name: "Brücke", cbm: 0.1 },
    { key: "deckenlampeAz", name: "Deckenlampe", cbm: 0.2 }
  ],

  "Kinderzimmer": [
    { key: "schrankBis2TuerenKZ", name: "Schrank, bis 2 Türen, nicht zerlegbar", cbm: 1.5 },
    { key: "schrankZerlegbarKZ", name: "Schrank, zerlegbar, je angef. m", cbm: 0.8 },
    { key: "bettKomplettKZ", name: "Bett, komplett", cbm: 1.0 },
    { key: "kinderbett", name: "Kinderbett, komplett", cbm: 0.5 },
    { key: "etagenbett", name: "Etagenbett, komplett", cbm: 1.6 },
    { key: "bettzeugKZ", name: "Bettzeug, je Betteinheit", cbm: 0.3 },
    { key: "nachttischKZ", name: "Nachttisch", cbm: 0.2 },
    { key: "kommodeKZ", name: "Kommode", cbm: 0.7 },
    { key: "schreibpult", name: "Schreibpult", cbm: 0.7 },
    { key: "spielkiste", name: "Spielkiste", cbm: 0.4 },
    { key: "regaleKZ", name: "Regale", cbm: 0.4 },
    { key: "tischBis1_0mKZ", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "rutsche", name: "Rutsche", cbm: 0.6 },
    { key: "tischUeber1_2mKZ", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "laufgitter", name: "Laufgitter", cbm: 0.1 },
    { key: "kinderregalNieder", name: "Kinderregal nieder", cbm: 0.2 },
    { key: "teppichKZ", name: "Teppich", cbm: 0.3 },
    { key: "brueckeKZ", name: "Brücke", cbm: 0.1 },
    { key: "anbauwandBis38cmKZ", name: "Anbauwand, bis 38 cm Tiefe, je angef. m", cbm: 0.8 },
    { key: "anbauwandUeber38cmKZ", name: "Anbauwand, üb. 38 cm Tiefe, je angef. m", cbm: 1.0 },
    { key: "deckenlampeKZ", name: "Deckenlampe", cbm: 0.2 },
    { key: "pcMonitorDruckerKZ", name: "PC + Monitor +Kleindrucker", cbm: 0.3 },
    { key: "schubladen", name: "Schubladen", cbm: 0.1 },
    { key: "kleiderbehaelter", name: "Kleiderbehältnis", cbm: 0.6 },

    // Aliase Kinderzimmer
    { key: "regale", name: "Regale", cbm: 0.4 },
    { key: "tischUeber-12MKz", name: "Tisch, über 1,2 m", cbm: 0.8 },
    { key: "tischBis-10MKz", name: "Tisch, bis 1,0 m", cbm: 0.5 },
    { key: "kinderbettKomplett", name: "Kinderbett, komplett", cbm: 0.5 },
    { key: "etagenbettKomplett", name: "Etagenbett, komplett", cbm: 1.6 },
    { key: "bettzeugJeBetteinheitKz", name: "Bettzeug, je Betteinheit", cbm: 0.3 },
    { key: "teppichKz", name: "Teppich", cbm: 0.3 },
    { key: "brueckeKz", name: "Brücke", cbm: 0.1 },
    { key: "deckenlampeKz", name: "Deckenlampe", cbm: 0.2 },
    { key: "pc-+Monitor-+kleindruckerkz", name: "PC + Monitor + Kleindrucker", cbm: 0.3 },
    { key: "schrankZerlegbarJeAngefMKz", name: "Schrank, zerlegbar, je angef. m", cbm: 0.8 },
    { key: "schrankBis-2TuerenNichtZerlegbarKz", name: "Schrank, bis 2 Türen, nicht zerlegbar", cbm: 1.5 },
    { key: "kleiderbehaeltnis", name: "Kleiderbehältnis", cbm: 0.6 },
    { key: "buecherregalNieder", name: "Bücherregal nieder", cbm: 0.2 },
    { key: "nachttischKz", name: "Nachttisch", cbm: 0.2 },
    { key: "kommodeKz", name: "Kommode", cbm: 0.7 }
  ],

  "Sonstiges": [
    { key: "fahrrad", name: "Fahrrad", cbm: 0.5 },
    { key: "dreirad", name: "Dreirad / Kinderrad", cbm: 0.2 },
    { key: "buegelbrett", name: "Bügelbrett", cbm: 0.1 },
    { key: "staubsauger", name: "Staubsauger", cbm: 0.1 },
    { key: "autoreifen", name: "Autoreifen", cbm: 0.1 },
    { key: "koffer", name: "Koffer", cbm: 0.1 },
    { key: "klapptischKlappstuhl", name: "Klapptisch /Klappstuhl", cbm: 0.2 },
    { key: "kinderwagen", name: "Kinderwagen", cbm: 0.5 },
    { key: "leiter", name: "Leiter, je angefangene m", cbm: 0.1 },
    { key: "rasenmaeherMotor", name: "Rasenmäher, Motor", cbm: 0.5 },
    { key: "rasenmaeherHand", name: "Rasenmäher, Hand", cbm: 0.2 },
    { key: "moped", name: "Moped", cbm: 0.8 },
    { key: "schubkarre", name: "Schubkarre", cbm: 0.4 },
    { key: "werkbank", name: "Werkbank,zerlegbar", cbm: 0.4 },
    { key: "werkzeugschrank", name: "Werkzeugschrank", cbm: 0.2 },
    { key: "werkzeugkoffer", name: "Werkzeugkoffer", cbm: 0.1 },
    { key: "ski", name: "Ski", cbm: 0.2 },
    { key: "schlitten", name: "Schlitten", cbm: 0.2 },
    { key: "blumenkuebel", name: "Blumenkübel / Kasten", cbm: 0.1 },
    { key: "sonnenschirm", name: "Sonnenschirm", cbm: 0.2 },
    { key: "tischtennisplatte", name: "Tischtennisplatte", cbm: 0.3 },
    { key: "muelltonne", name: "Mülltonne", cbm: 0.2 },
    { key: "regalZerlegbarSonstige", name: "Regal, zerlegbar, je angef. M", cbm: 0.4 },
    { key: "hometrainer", name: "Hometrainer", cbm: 1.8 },

    // Aliase Sonstiges
    { key: "blumenkuebel-/Kasten", name: "Blumenkübel / Kasten", cbm: 0.1 },
    { key: "tischrennisplatte", name: "Tischtennisplatte", cbm: 0.3 },
    { key: "2CdStaender", name: "CD-Ständer", cbm: 0.1 },
    { key: "klapptisch-/klappstuhl", name: "Klapptisch / Klappstuhl", cbm: 0.2 },
    { key: "werkbankzerlegbar", name: "Werkbank, zerlegbar", cbm: 0.4 },
    { key: "leiterJeAngefangeneM", name: "Leiter, je angefangene m", cbm: 0.1 },
    { key: "dreirad-/Kinderrad", name: "Dreirad / Kinderrad", cbm: 0.2 },
    { key: "regalZerlegbarJeAngefM", name: "Regal, zerlegbar, je angef. m", cbm: 0.4 }
  ],

  "Universal": [
    { key: "kleineUmzugskartons", name: "Kleine Umzugskartons", cbm: 0.1 },
    { key: "mittlereUmzugskartons", name: "Mittlere Umzugskartons", cbm: 0.15 },
    { key: "grosseUmzugskartons", name: "Große Umzugskartons", cbm: 0.2 },

    // generische Aliase (raumunabhängig)
    { key: "stuhl-/Hocker", name: "Stuhl / Hocker", cbm: 0.2 },
    { key: "stuhl-", name: "Stuhl", cbm: 0.2 },
    { key: "stuhlMitArmlehnen", name: "Stuhl, mit Armlehnen", cbm: 0.3 },
    { key: "deckenlampe", name: "Deckenlampe", cbm: 0.2 },
    { key: "bruecke", name: "Brücke", cbm: 0.1 },
    { key: "blumenGroesse-", name: "Blumen (Größe)", cbm: 0.1 },
    { key: "blumenGoesse", name: "Blumen (Größe)", cbm: 0.1 }
  ]
} as const;
